require('dotenv').config();
const express = require('express');
const mysql = require('mysql2/promise');
const cors =  require('cors');
const bodyParser = require('body-parser');
const multer = require('multer');
const path = require('path');
const fs = require('fs');
const compression = require('compression');
const brypt = require('bcrypt');
const jwt = require('jsonwebtoken');